### ISSUE TITLE
Dúvidas em relação a teste

### ISSUE THREAD

**Issue by Anjokr** [itau-canais-estag/teste-estag-canais#2]
Alguns pontos não estão claros para mim neste teste:
- ordem das variáveis podem variar? Não está claro o papel/necessidade da primeira linha no arquivo de entrada (atualmente estou programando assumindo que sim)
- é apenas uma transferência mesmo que irá acontecer para cada execução de programa? Ou terá mais linhas após a segunda no arquivo de entrada?
- como ocorre a transferência se o emissor começa com saldo zerado, possuindo nada para poder transferir ao receptor?

**Comment by IvanCost** [comment]
Oi @Anjokr, conforme descrito no enunciado, a primeira linha do arquivo representa as variáveis e a segunda linha os valores possíveis para cada uma das variáveis. Assuma que todos os valores sempre estarão preenchidos e sempre na mesma ordem. 

![Captura de Tela 2022-05-09 às 09 21 54](https://user-images.githubusercontent.com/44673881/167408860-627d3b1b-06fa-4bc5-8e10-2bec41d3dfe0.png)

Teremos um arquivo txt para cada transação testada.

Sendo o saldo do emissor = R$ 0,00, uma vez feita uma transferência, ele ficará com saldo negativo.
